// Downloads the latin subsets of our four families from Google Fonts and
// self-hosts them, so the site makes no third-party request for type.
// Re-run with `npm run fonts` if the font stack changes.
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const FAMILIES = [
  // Fraunces carries the headings — a warm, slightly wonky serif that reads
  // editorial rather than corporate. Figtree does body, UI and labels.
  'Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,600;0,9..144,700;1,9..144,400;1,9..144,600',
  'Figtree:wght@400;500;600;700',
]
const KEEP = new Set(['latin', 'latin-ext'])
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

const OUT_DIR = 'public/fonts'
await mkdir(OUT_DIR, { recursive: true })

const url = `https://fonts.googleapis.com/css2?${FAMILIES.map((f) => `family=${f}`).join('&')}&display=swap`
const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text()

// Google's CSS emits one @font-face per subset, each preceded by a /* subset */ comment.
const blocks = css.split('/*').slice(1)
const out = []
let downloaded = 0

for (const block of blocks) {
  const subset = block.slice(0, block.indexOf('*/')).trim()
  if (!KEEP.has(subset)) continue

  const face = block.slice(block.indexOf('*/') + 2)
  const src = face.match(/url\((https:\/\/[^)]+\.woff2)\)/)
  if (!src) continue

  const family = face.match(/font-family:\s*'([^']+)'/)?.[1] ?? 'font'
  const weight = face.match(/font-weight:\s*(\d+)/)?.[1] ?? '400'
  const style = face.match(/font-style:\s*(\w+)/)?.[1] ?? 'normal'
  const file = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}${style === 'italic' ? '-italic' : ''}-${subset}.woff2`

  const buf = Buffer.from(await (await fetch(src[1], { headers: { 'User-Agent': UA } })).arrayBuffer())
  await writeFile(path.join(OUT_DIR, file), buf)
  downloaded++

  out.push(
    face
      .replace(src[0], `url(/fonts/${file})`)
      .trim()
      .replace(/^@font-face\s*\{/, '@font-face {'),
  )
}

await writeFile(
  'src/fonts.css',
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n${out.join('\n\n')}\n`,
)
console.log(`downloaded ${downloaded} woff2 files -> ${OUT_DIR}`)
console.log('wrote src/fonts.css')
